#!/usr/bin/env python3

import subprocess
import argparse
import sys

def run_tmux_command(command):
    try:
        result = subprocess.check_output(command, shell=True, text=True)
        return result.strip().split('\n')
    except subprocess.CalledProcessError as e:
        print(f"Error running command: {e}")
        return []

def send_keys_to_tmux(window_index, pane_index, command, session=None):
    target = f"{window_index}.{pane_index}" if pane_index is not None else window_index
    if session:
        target = f"{session}:{target}"
    command = f"tmux send-keys -t {target} '{command}' C-m"
    subprocess.run(command, shell=True)

## Get TMUX

def get_windows_list(session=None):
    if session:
        command = f"tmux list-windows -t {session} -F '#{{window_index}} #{{window_name}}'"
    else:
        command = f"tmux list-windows -F '#{{window_index}} #{{window_name}}'"
    return [tuple(line.split(' ')) for line in run_tmux_command(command)]

def get_panes_in_windows_list(window_index, session):
    if session:
        command = f"tmux list-panes -t {session}:{window_index} -F '#{{pane_index}}'"
    else:
        command = f"tmux list-panes -t {window_index} -F '#{{pane_index}}'"
    return run_tmux_command(command)
    
def is_tmux_session_exists(session_name):
    try:
        subprocess.check_output(['tmux', 'has-session', '-t', session_name], stderr=subprocess.STDOUT)
        return True
    except subprocess.CalledProcessError as e:
        return False

## Select TMUX

def select_window(window_list):
    if not window_list:
        print("No Tmux windows found.")
        return None
    print("Available Tmux windows:")
    for index, (window_index, window_name) in enumerate(window_list):
        print(f"{index + 1}: {window_name}")

    selected_window = int(input("Select a window (enter the number): ")) - 1
    return window_list[selected_window] if 0 <= selected_window < len(window_list) else None

def select_pane(pane_indices):
    if len(pane_indices) == 1:
        return pane_indices[0]

    print(f"Available panes:")
    for index, pane_index in enumerate(pane_indices):
        print(f"{index + 1}: Pane {pane_index}")

    selected_pane = int(input("Select a pane (enter the number): ")) - 1
    return pane_indices[selected_pane] if 0 <= selected_pane < len(pane_indices) else None

## Run Script

def process_args(window_list, args):
    window_input = args.window_input
    parts = window_input.split('.')

    if len(parts) == 1:
        # Format: script.py $WINDOW
        window_input = parts[0]
        pane_index = 1  # Always use pane 1
    elif len(parts) == 2:
        # Format: script.py $WINDOW.$PANE
        window_input, pane_index = parts
    else:
        sys.exit("Invalid window format.")

    for window_index, window_name in window_list:
        if window_index == window_input or window_name == window_input:
            return window_index, pane_index
    
    return None, None

def run_args_passed(args):
    if((args.session is not None) and (not is_tmux_session_exists(args.session))):
        sys.exit(f"Session '{args.session}' not found")

    window_list = get_windows_list(args.session)
    window_index, pane_index = process_args(window_list, args)

    if not window_list:
        sys.exit("No Tmux windows found.")
        return

    if window_index is not None:
        send_keys_to_tmux(window_index, pane_index, args.command, args.session)
    else:
        sys.exit("Window not found.")

def prompt_user_input(args): 
    if((args.session is not None) and (not is_tmux_session_exists(args.session))):
        sys.exit(f"Session '{args.session}' not found")

    # TODO: Make this cleaner
    window_list = get_windows_list(args.session)
    selected_window = select_window(window_list)

    if selected_window:
        window_index, _ = selected_window
        pane_indices = get_panes_in_windows_list(window_index, args.session)
        selected_pane = select_pane(pane_indices)
    else:
        print("Invalid window selection.")

    if selected_pane:
        command = input("Enter the string to send: ")
        send_keys_to_tmux(window_index, selected_pane, command, args.session)
    else:
        print("Invalid pane selection.")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Send keys to a specific tmux window and pane")
    parser.add_argument("window_input", nargs="?", help="Specify the window and optionally pane (e.g., '$window or $window.$pane')")
    parser.add_argument("command", nargs="?", help="The command to send to the tmux window")
    parser.add_argument("-s", "--session", help="Specify the tmux session name")
    args = parser.parse_args()

    if((args.window_input is not None) and (args.command is not None)): 
        run_args_passed(args)
    else: 
        prompt_user_input(args)
