#!/usr/bin/env bash
THEME='Catppuccin-Mocha-Standard-Mauve-Dark'
FONT='Fantasque Sans Mono'
CURSOR='Sweet'

SCHEMA='gsettings set org.gnome.desktop.interface'

# apply_themes () {
# 	${SCHEMA} gtk-theme "$THEME"
# 	# ${SCHEMA} icon-theme "$ICONS"
# 	${SCHEMA} cursor-theme "$CURSOR"
# 	${SCHEMA} font-name "$FONT"
# }



# apply_themes () {
# 	${SCHEMA} gtk-theme "$THEME"
# 	${SCHEMA} font-name "$FONT"
# }


# apply_themes
