#!/bin/bash

SCRIPTSDIR=$HOME/.dotfiles/scripts/hypr

# Kill already running process
_ps=(waybar mako)
for _prs in "${_ps[@]}"; do
	if [[ $(pidof ${_prs}) ]]; then
		killall -9 ${_prs}
	fi
done


# Apply themes
${SCRIPTSDIR}/core/gtkthemes &

# Lauch notification daemon (mako)
${SCRIPTSDIR}/core/notifications &

# Lauch statusbar (waybar)
${SCRIPTSDIR}/core/statusbar &
